"""Add attendance_date column

Revision ID: 4b1ba7bba847
Revises: 
Create Date: 2024-03-13 14:13:38.510928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1ba7bba847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.drop_column('attendance_date')

    # ### end Alembic commands ###
