"""add file_path field to Database model

Revision ID: 941272ba043a
Revises: 4b1ba7bba847
Create Date: 2024-03-14 12:16:44.563633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941272ba043a'
down_revision = '4b1ba7bba847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
